export const FETCH_OFFERS = "FETCH_OFFERS",
             DETAIL_OFFER = "DETAIL_OFFER",
             SET_FILTERS = "SET_FILTERS",
             REMOVE_FILTER = "REMOVE_FILTER",
             CLEAR_FILTERS = "CLEAR_FILTERS",
             SET_SUBJECTS = "SET_SUBJECTS",
             SET_UNIVERSITIES = "SET_UNIVERSITIES";