export const FETCH_OFFERS = "FETCH_OFFERS",
             DETAIL_OFFER = "DETAIL_OFFER",
             SET_FILTERS = "SET_FILTERS",
             REMOVE_FILTER = "REMOVE_FILTER",
             SET_SUBJECTS = "SET_SUBJECTS";