// Fetch offers
export const FECTH_OFFERS_LIST_START = 'FECTH_OFFERS_LIST_START'
export const FECTH_OFFERS_LIST_SUCCESS = 'FECTH_OFFERS_LIST_SUCCESS'
export const FECTH_OFFERS_LIST_ERROR = 'FECTH_OFFERS_LIST_ERROR'