// Fetch offers
export const FECTH_OFFERS_LIST_START = 'FECTH_OFFERS_LIST_START'
export const FECTH_OFFERS_LIST_SUCCESS = 'FECTH_OFFERS_LIST_SUCCESS'
export const CLEAR_AND_FETCH_OFFERS_LIST_SUCCESS = 'CLEAR_AND_FETCH_OFFERS_LIST_SUCCESS'
export const FILTER_AND_FETCH_LIST_SUCCESS = 'FILTER_AND_FETCH_LIST_SUCCESS'
export const FECTH_OFFERS_LIST_ERROR = 'FECTH_OFFERS_LIST_ERROR'

// Offers Detail
export const OFFER_DETAIL_START = 'OFFER_DETAIL_START'
export const OFFER_DETAIL_SUCCESS = 'OFFER_DETAIL_SUCCESS'
export const OFFER_DETAIL_ERROR = 'OFFER_DETAIL_ERROR'

// Default Search
export const SEARCH_START = 'SEARCH_START'
export const SEARCH_ERROR = 'SEARCH_ERROR'

// Courses Search
export const COURSES_SEARCH_SUCCESS = 'COURSES_SEARCH_SUCCESS'

// University Search
export const UNIVERTISY_SEARCH_SUCCESS = 'UNIVERTISY_SEARCH_SUCCESS'