// Fetch offers
export const FECTH_OFFERS_LIST_START = 'FECTH_OFFERS_LIST_START'
export const FECTH_OFFERS_LIST_SUCCESS = 'FECTH_OFFERS_LIST_SUCCESS'
export const FECTH_OFFERS_LIST_ERROR = 'FECTH_OFFERS_LIST_ERROR'

// Offers Detail
export const OFFER_DETAIL_START = 'OFFER_DETAIL_START'
export const OFFER_DETAIL_SUCCESS = 'OFFER_DETAIL_SUCCESS'
export const OFFER_DETAIL_ERROR = 'OFFER_DETAIL_ERROR'