export default {
  OFFER_REQ_ERROR: 'OFFER_REQ_ERROR',
  OFFER_REQ_DATA: 'OFFER_REQ_DATA',
  OFFER_RECV_DATA: 'OFFER_RECV_DATA',
  OFFER_RECV_INFO_DATA: 'OFFER_RECV_INFO_DATA',
  OFFER_RECV_SCROLL_DATA: 'OFFER_RECV_SCROLL_DATA',
  OFFER_RECV_REFRESH_DATA: 'OFFER_RECV_REFRESH_DATA',
  OFFER_RECV_FILTERED_DATA: 'OFFER_RECV_FILTERED_DATA'
};