platform :ios, '8.0'
use_frameworks!

def default_pods
  pod 'Fabric'
  pod 'Crashlytics'
end

target 'QueroEducacao' do
  default_pods    
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end
